### DISCUSSION TITLE
how do certain variable fallbacks get injected

### DISCUSSION THREAD

**Discussion by dsmmcken** [adobe/react-spectrum#5789] [Q&A]
Just curious how this works,. Some variables get a fallback(?), but I don't understand where they come from.

For example:
in adobe/spectrum-css-temp/components/table/skin.css

I can see it's defined as:
```css
  &.is-selected {
    .spectrum-Table-cell {
      background-color: var(--spectrum-table-row-background-color-selected);
    }
```
No where do I see `--spectrum-table-row-background-color-selected` defined. And then the output becomes:
```css
background-color: var(--spectrum-table-row-background-color-selected-hover,var(--spectrum-alias-highlight-selected-hover))
```

Where and how does `--spectrum-alias-highlight-selected-hover` get added? I see a bunch of post processing steps, but I don't see where that mapping would logically come from. Searching for `alias.*selected` doesn't reveal anything, so is the mapping from another an external package?

Would appreciate any insight, just trying to get a clear picture of how this all works, thanks.
