### DISCUSSION TITLE
Style React Aria Slots with Tailwind.

### DISCUSSION THREAD

**Discussion by brenotx** [adobe/react-spectrum#6400] [Q&A] [answered]
Hi, I wonder if it is possible to style React Slots with Tailwind.

The following approach is very common the React Aria docs, but I'd like to use Tailwind instead.
```css
.react-aria-ListBoxItem {
  [slot=label] {
    font-weight: bold;
  }

  [slot=description] {
    font-size: small;
  }
}
```

Perhaps something like `className="[slot=description]:text-sm"`
