### DISCUSSION TITLE
`group-invalid` not applying properly with tailwindcss v4?

### DISCUSSION THREAD

**Discussion by devlzcode** [adobe/react-spectrum#7518] [Q&A]
This is the resolved CSS:
```css
.group-invalid\:border-negative-900 {
    border-color: var(--color-negative-900) /* #ff9581 */;
}
```

For comparison this is without `group-`:
```css
.invalid\:border-negative-900 {
    &:where([data-rac])[data-invalid] {
        border-color: var(--color-negative-900) /* #ff9581 */;
    }
    &:where(:not([data-rac])):invalid {
        border-color: var(--color-negative-900) /* #ff9581 */;
    }
}
```

Group modifier does work with other states, just not this one. Here is `group-disabled`
```css
.group-disabled\:cursor-not-allowed {
    :merge(.group):where([data-rac])[data-disabled] & {
        cursor: not-allowed;
    }
    :merge(.group):where(:not([data-rac])):disabled & {
        cursor: not-allowed;
    }
}
```
