### ISSUE TITLE
Action Buttons displaying tiny icons

### ISSUE THREAD

**Issue by deloreyj** [adobe/react-spectrum#1042]
# 🐛 Bug Report 
When used on a site that sets box-sizing with the [univeral box sizing with inheritance](https://css-tricks.com/box-sizing/#universal-box-sizing-with-inheritance) approach, the icons inside of action buttons appear tiny. 
```css
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```

## 🤔 Expected Behavior
Icons should appear normal size regardless of global box sizing rules
![image](https://user-images.githubusercontent.com/6365144/91910068-f7bd6480-ec73-11ea-8af1-0b9b3c9d5199.png)

## 😯 Current Behavior
Icon appears tiny inside action button
![image](https://user-images.githubusercontent.com/6365144/91909989-d52b4b80-ec73-11ea-8c14-474e174c6d0f.png)

## 💁 Possible Solution
It appears to be happening because the <svg> inside the action button does not define a `box-sizing` rule, which typically works because it expects the default `content-box`. One solution would be to add a style rule like the following to prevent the svg from inheriting
```css
.ActionButton svg {
  box-sizing: initial
}

or

.ActionButton svg {
  box-sizing: unset
}
```

## 🔦 Context
Magento runs react-spectrum UI inside the Magento shell and the shell CSS causes this bug in all our apps

## 💻 Code Sample

https://github.com/deloreyj/spectrum-action-button/tree/master

## 🧢 Your Company/Team
Adobe Magento
