### ISSUE TITLE
Not able to override base font to the one of our choice

### ISSUE THREAD

**Issue by aroraumang** [adobe/react-spectrum#2788]
# 🐛 Bug Report 

Not able to override base font to the one of our choice.

## 🤔 Expected Behavior

I tried to change the variables `--spectrum-font-family-base` and `--spectrum-global-font-family-base`, but that didn't seem to have any effect

## 😯 Current Behavior

Should change the font to the one I have specified

## 💻 Code Sample

```js
<Provider theme={defaultTheme} colorScheme="light">
  <Provider
    theme={{
      global: { spectrum_global: 'spectrum_global' },
      light: { spectrum_light: 'spectrum_light' },
      dark: { spectrum_dark: 'spectrum_dark' },
      large: { spectrum_large: 'spectrum_large' },
      medium: { spectrum_medium: 'spectrum_medium' },
    }}
  >
    <Button variant="cta">Hello World</Button>
  </Provider>
</Provider>
```

css in `spectrum_global` class:

```css
.spectrum_global {
  --spectrum-alias-border-radius-large: 5px;
  --spectrum-global-font-family-base: monospace;
  --spectrum-font-family-base: monospace;
}
```
Note: The variable `--spectrum-alias-border-radius-large` is working fine, so the custom theming seems to be working fine. Just not the fonts.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.15.1
| Browser          | Chrome Version 97.0.4692.99
| Operating System | macOS Monterey v12.0.1
