### ISSUE TITLE
In FocusRing if we give css to focusClass, focus ring is not disappeared on loosing focus

### ISSUE THREAD

**Issue by upender7270** [adobe/react-spectrum#3317]
# 🐛 Bug Report 
In FocusRing if we give CSS to focusClass, CSS is not disappearing after losing focus. When we give CSS to the focusRingClass it is working as expected. But focusRingClass is only for CSS class to apply when the element has keyboard focus, I want mouse actions as well.

## 🤔 Expected Behavior
When we click outside the button, outline CSS should be disappeared 

## 😯 Current Behavior
When we click outside the button, outline CSS is not disappearing

## 💻 Code Sample
```css
.button {
  -webkit-appearance: none;
  appearance: none;
  background: green;
  border: none;
  color: white;
  font-size: 14px;
  padding: 4px 8px;
}

.button.focus-ring {
  outline: 2px solid dodgerblue;
  outline-offset: 2px;
}
```
```JSX
import {FocusRing} from '@react-aria/focus';

<FocusRing focusClass="focus-ring">
  <button className="button">Test</button>
</FocusRing>
```
Click the tab to focus button and click outside to check.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |Chrome, Brave
| Operating System |Mac OS, Ubutntu
