### ISSUE TITLE
Express theme should render a border on Popovers and Dialogs with forced-colors: active

### ISSUE THREAD

**Issue by majornista** [adobe/react-spectrum#4049]
# 🐛 Bug Report 

Using Express theme, Popovers and Dialogs should render a border with `forced-colors: active` or Windows High Contrast Mode.

## 🤔 Expected Behavior

Using Express theme, Popovers and Dialogs should render a border with `forced-colors: active` or Windows High Contrast Mode.

## 😯 Current Behavior

Using Express theme, Popovers do not render a border with `forced-colors: active` or Windows High Contrast Mode.

## 💁 Possible Solution

For popovers, in [/packages/%40adobe/spectrum-css-temp/vars/express.css](https://github.com/adobe/react-spectrum/blob/be0fae9f7952f4d09823498dc1f251e13842f338/packages/%40adobe/spectrum-css-temp/vars/express.css#L164), add `@media (forced-colors: active)` with override of border-width: 

```css
@media (forced-colors: active) {
  .express.express {
    --spectrum-popover-border-size: var(--spectrum-alias-border-size-thin);
  }
}
```

For dialogs, in [/packages/@adobe/spectrum-css-temp/components/dialog/skin.css](https://github.com/adobe/react-spectrum/blob/be0fae9f7952f4d09823498dc1f251e13842f338/packages/@adobe/spectrum-css-temp/components/dialog/skin.css#L39), add `@media (forced-colors: active)` with override of border-width: 

```css
@media (forced-colors: active) {
  .spectrum-Dialog:not(.spectrum-Dialog--fullscreenTakeover) {
    border: var(--spectrum-alias-border-size-thin) solid transparent;
  }
}
```

Also, for design elegance, include a border radius at: [packages/@adobe/spectrum-css-temp/components/dialog/index.css](https://github.com/adobe/react-spectrum/blob/be0fae9f7952f4d09823498dc1f251e13842f338/packages/@adobe/spectrum-css-temp/components/dialog/index.css#L532):

```css
@media (forced-colors: active) {
  .spectrum-Dialog:not(.spectrum-Dialog--fullscreenTakeover) {
    border-radius: var(--spectrum-dialog-border-radius);
  }
}
```

## 🔦 Context

Accessibility audit.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  [@adobe/react-spectrum@3.24.1](https://github.com/adobe/react-spectrum/releases/tag/%40adobe%2Freact-spectrum%403.24.1)
| Browser          |  Chrome Version 110.0.5481.77 (Official Build) (arm64)
| Operating System | macOS Ventura 13.2 (22D49)

## 🧢 Your Company/Team

Adobe/Accessibility

## 🕷 Tracking Issue (optional)

A11Y-5803
