### ISSUE TITLE
NumberField issue with flex layout and forms 

### ISSUE THREAD

**Issue by majornista** [adobe/react-spectrum#4200]
# 🐛 Bug Report 

See https://reactspectrum.blob.core.windows.net/reactspectrum/4a7576870d4dbe80cdbebba2043f593474ad6cb4/storybook/index.html?path=/story/form--form-with-numberfield-and-locale-ar-ae&providerSwitcher-express=false

## 🤔 Expected Behavior

<img width="775" alt="Screenshot of NumberField decrement button layout bug fix within a flex layout" src="https://user-images.githubusercontent.com/154077/225110488-8d9b7755-dfc0-4694-b09e-96fb3a34e1ba.png" />

## 😯 Current Behavior

<img width="775" alt="Screenshot of NumberField decrement button layout bug within a flex layout" src="https://user-images.githubusercontent.com/154077/225102687-eef267ae-fa98-40b0-9f64-07b5087dd6cd.png" />

## 💁 Possible Solution

At
https://github.com/adobe/react-spectrum/blob/4a7576870d4dbe80cdbebba2043f593474ad6cb4/packages/%40adobe/spectrum-css-temp/components/fieldlabel/index.css#L84-L88

add `align-self: start;`:
```css
    .spectrum-Field-field {
      /* If the user overrides the width of the field, propagate to the inner component */
      width: 100%;
      grid-area: field;
      align-self: start;
    }
```

and at:
https://github.com/adobe/react-spectrum/blob/4a7576870d4dbe80cdbebba2043f593474ad6cb4/packages/%40adobe/spectrum-css-temp/components/fieldlabel/index.css#L119-L122

add `align-self: start;`:
```css
      .spectrum-Field-field {
        /* If the user overrides the width of the field, propagate to the inner component */
        width: 100%;
      }
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | @adobe/react-spectrum@3.25.1
| Browser          | Chrome Version 110.0.5481.177 (Official Build) (arm64)
| Operating System | macOS Ventura 13.2.1 (22D68)

## 🧢 Your Company/Team

Adobe/Accessibility
