### ISSUE TITLE
[dialog, gridlist, tag]: Yarn peerDependency error

### ISSUE THREAD

**Issue by wojtekmaj** [adobe/react-spectrum#4934]
### Provide a general summary of the issue here

During installation with Yarn:

```
➤ YN0002: │ @react-aria/dialog@npm:3.5.3 [3f49c] doesn't provide react-dom (p96c22), requested by @react-aria/overlays
➤ YN0002: │ @react-aria/gridlist@npm:3.5.0 [3f49c] doesn't provide react-dom (pfcf3b), requested by @react-aria/grid
```

### 🤔 Expected Behavior?

peerDependencies should be correctly defined.

### 😯 Current Behavior

peerDependencies are not correctly defined.

### 💁 Possible Solution

I'm using the following workaround:

```
packageExtensions:
  '@react-aria/dialog@*':
    peerDependencies:
      'react-dom': '^16.8.0 || ^17.0.0-rc.1 || ^18.0.0'
  '@react-aria/gridlist@*':
    peerDependencies:
      'react-dom': '^16.8.0 || ^17.0.0-rc.1 || ^18.0.0'
  '@react-aria/tag@*':
    peerDependencies:
      'react-dom': '^16.8.0 || ^17.0.0-rc.1 || ^18.0.0'
```

And most likely, the reflection of these "package extensions" should be made in packages' respective package.json files.

### 🖥️ Steps to Reproduce

yarn install react-aria

### Version

3.26.0

### What browsers are you seeing the problem on?

Other

### If other, please specify.

n/a

### What operating system are you using?

macOS Ventura
