### ISSUE TITLE
Multiple empty :is() selectors in generated CSS

### ISSUE THREAD

**Issue by golinski** [adobe/react-spectrum#5310]
### Provide a general summary of the issue here

After creating an empty `react-ts` project with `vite`, installing the latest @adobe/react-spectrum in it, and changing `App.tsx` to this:

```js
import { Button } from '@adobe/react-spectrum'

function App() {
  return <Button variant="accent">Save</Button>;
}

export default App
```

after a production build we get CSS with several empty `:is()` and `:-webkit-any()` selectors like these:

```css
:is() .uFrYBa_spectrum-BarLoader-percentage{
    color:var(--spectrum-barloader-large-over-background-track-fill-color,var(--spectrum-global-color-static-white))
}
:-webkit-any() .uFrYBa_spectrum-BarLoader-track{
    background-color:var(--spectrum-barloader-large-over-background-track-color,var(--spectrum-alias-track-color-over-background))
}
```
Same issue with create-react-app, in fact these are already present in the files distributed in react-spectrum packages, e.g., `@react-spectrum/button/dist/main.css`

### 🤔 Expected Behavior?

No such empty rules are emitted/present.

### 😯 Current Behavior

Rules like that are created which probably cannot match any elements.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/wonderful-diffie-w8pfwl

### Version

3.31.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

Linux
