### ISSUE TITLE
RAC DatePicker: match popover width to field width

### ISSUE THREAD

**Issue by emlai** [adobe/react-spectrum#5883]
### Provide a general summary of the feature here

I want to make the calendar popover of DatePicker have the same width as the field.

### 🤔 Expected Behavior?

The docs provide a way to make the popover width match the field width.

### 😯 Current Behavior

Didn't find a way to accomplish this in the docs.

### 💁 Possible Solution

`Select` supports the `--trigger-width` CSS variable for the same use case. That could be a possible solution.

```css
.react-aria-Popover[data-trigger=Select] {
  min-width: var(--trigger-width);
}
```

### 🔦 Context

<img width="376" alt="Screenshot 2024-02-15 at 17 52 49" src="https://github.com/adobe/react-spectrum/assets/7543552/f3940e65-b975-4cab-8def-bb0610b2f33c">
