### ISSUE TITLE
peerDependency issue with multiple react-aria packages

### ISSUE THREAD

**Issue by wojtekmaj** [adobe/react-spectrum#7644]
### Provide a general summary of the issue here

The latest version of react-aria-components, 1.5.0, is breaking under Yarn PnP due to undeclared peerDependencies.

@react-aria/utils@3.27.0 added peerDependency on react-dom, but this change was not reflected in all packages using @react-aria/utils, breaking peerDependency chains.

### 🤔 Expected Behavior?

No error on module resolution, no peerDependency warnings

### 😯 Current Behavior

```
Error: @react-aria/utils tried to access react-dom (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: react-dom (via "react-dom/package.json")
Required by: @react-aria/utils@virtual:33bcd16335789050108ea9838c8a03f9b565af286e9a92946d0468f5f7565416cf9576f65aeceb111f05bc67c8ba45f8558e7817e59c5c520028d412fd8d633f#npm:3.27.0 (via /home/vsts/work/1/s/.yarn/__virtual__/@react-aria-utils-virtual-33891fb570/1/~/.yarn/berry/cache/@react-aria-utils-npm-3.27.0-e59b5700ea-10c0.zip/node_modules/@react-aria/utils/dist/animation.mjs)

Ancestor breaking the chain: @react-aria/meter@virtual:e4b6340ba908bc3b576b8982a53902de55d03189d8a08cbc784349de930b4098979d63269be19d8a2775c175203d69143c92674bd8752e7d6dd5b3098a9955c8#npm:3.4.19
Ancestor breaking the chain: @react-aria/switch@virtual:e4b6340ba908bc3b576b8982a53902de55d03189d8a08cbc784349de930b4098979d63269be19d8a2775c175203d69143c92674bd8752e7d6dd5b3098a9955c8#npm:3.6.11
Ancestor breaking the chain: @react-stately/layout@virtual:bc24a98cbb0408262fd7edb6c767cdd7914a4352c630f6ad1e38cd492cb3bd152e4d21d350026ecbc89edd907ea34c6c06937cf11f66e8c507b88ab245f00b12#npm:4.1.1


 ❯ makeError ../../.pnp.cjs:21655:34
 ❯ resolveToUnqualified ../../.pnp.cjs:23254:21
 ❯ Object.resolveToUnqualified ../../.pnp.cjs:23483:26
 ❯ resolve$1 ../../.pnp.loader.mjs:2033:31

```

### 💁 Possible Solution

A workaround is to add:

```
packageExtensions:
  '@react-aria/meter@^3.4.19':
    peerDependencies:
      react-dom: ^16.8.0 || ^17.0.0-rc.1 || ^18.0.0 || ^19.0.0-rc.1
  '@react-aria/switch@^3.6.11':
    peerDependencies:
      react-dom: ^16.8.0 || ^17.0.0-rc.1 || ^18.0.0 || ^19.0.0-rc.1
  '@react-stately/layout@^4.1.1':
    peerDependencies:
      react-dom: ^16.8.0 || ^17.0.0-rc.1 || ^18.0.0 || ^19.0.0-rc.1
```

to .yarnrc.yml, and this workaround provides a glimpse on how to resolve the issue in RAC itself.

### 🖥️ Steps to Reproduce

Install RAC using Yarn in PnP, try to import any of the packages mentioned above.

### Version

1.6.0

### What browsers are you seeing the problem on?

Other

### If other, please specify.

n/a

### What operating system are you using?

n/a
